### ISSUE TITLE
Rich Picture

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#1]
## Descrição
Criação e documentação dos Rich Pictures.

## Tarefas
- [x] Gabriel
- [x] Gabriel Davi
- [x] Micaella
- [x] Sofia
- [x] Pedro

**Comment by micaellagouveia** [comment]
Coloquei a minha versão do rich picture em nosso drive na pasta Documentos/RichPicture.

**Comment by pedroeagle** [comment]
Também coloquei minha versão do Rich Picture no nosso drive na pasta Documentos/Rich Picture.

**Comment by sofiapatrocinio** [comment]
Coloquei a minha versão do rich picture em nosso drive na pasta Documentos/RichPicture.
