### ISSUE TITLE
Criação da sidebar e navbar

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#178]
## Descrição
Elaboração da sidebar e navbar da aplicação.

### Critérios de aceitação

- [x] Se aplicar para todas as páginas pós login
- [x] Responsividade

**Comment by sofiapatrocinio** [comment]
![screenshot_2](https://user-images.githubusercontent.com/38709421/97308723-f194d000-183f-11eb-8523-e92d87215462.png)
