### ISSUE TITLE
Estudo Dirigido - Estilos e Padrões Arquiteturais (Parte III)

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#179]
## Descrição
Estudo dirigido sobre arquitetura - Parte III

**Comment by sofiapatrocinio** [comment]
![screenshot_3](https://user-images.githubusercontent.com/38709421/97308758-fb1e3800-183f-11eb-96a0-3fe00404a09d.png)
