### ISSUE TITLE
Estudo Dirigido - Módulo Estilos e Padrões Arquiteturais (Partes I e II)

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#180]
## Descrição
Estudo sobre Arquitetura - Padrões Arquiteturais I e II

**Comment by sofiapatrocinio** [comment]
![screenshot_4](https://user-images.githubusercontent.com/38709421/97308811-0bceae00-1840-11eb-982e-1c8b4884394a.png)
