### ISSUE TITLE
Estudo Dirigido - Módulo Estilos e Padrões Arquiteturais (Parte IV)

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#181]
## Descrição
Estudo sobre Padrões Arquiteturais Parte IV.

**Comment by sofiapatrocinio** [comment]
![screenshot_5](https://user-images.githubusercontent.com/38709421/97308856-1721d980-1840-11eb-965b-270d61e8578b.png)
