### ISSUE TITLE
Evolução do Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#183]
## Descrição
Criação das telas relacionadas a produto, categoria e lote no protótipo de alta fidelidade.

**Comment by sofiapatrocinio** [comment]
![screenshot_7](https://user-images.githubusercontent.com/38709421/97308914-2bfe6d00-1840-11eb-814c-87206bc74afd.png)
