### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#2]
## Descrição
Criar e documentar mapas mentais.

## Tarefas
- [x] Gabriel
- [x] Gabriel Davi
- [x] Micaella
- [x] Sofia
- [x] Pedro

**Comment by micaellagouveia** [comment]
Coloquei a minha versão do mapa mental em nosso drive na pasta Documentos/MapaMental.

**Comment by sofiapatrocinio** [comment]
Coloquei a minha versão do mapa mental em nosso drive na pasta Documentos/MapaMental.

**Comment by pedroeagle** [comment]
Adicionei meu mapa mental ao nosso drive na pasta Documentos/MapaMental
