### ISSUE TITLE
US28 - Gráfico de Fluxo de Saída

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#205]
## Descrição
Eu como usuário Admin/Owner desejo visualizar gráficos baseados no fluxo de estoque

### Tasks: 
- [x] Criação de gráfico de acordo com rota de decreases

### Critérios de aceitação

- [x] Estar de acordo com o protótipo
- [x] Ser responsivo

**Comment by micaellagouveia** [comment]
Pontuação da Issue:
![us28](https://user-images.githubusercontent.com/48630408/99151293-d49e3080-2678-11eb-9e8d-a814b2810adb.png)
