### ISSUE TITLE
US29 - Gráfico de Vendas por Semana

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#206]
## Descrição
Eu como usuário Admin/Owner desejo visualizar gráficos que marcam o periodo por quantidade total de produto

### Tasks: 
- [ ] Criação de gráfico de acordo com rota de products

### Critérios de aceitação

- [ ] Estar de acordo com o protótipo
- [ ] Ser responsivo

**Comment by micaellagouveia** [comment]
Pontuação da issue:
![us29](https://user-images.githubusercontent.com/48630408/99151300-e8499700-2678-11eb-8269-bf78c08ad37b.png)
