### ISSUE TITLE
US30 - Gráfico Produtos por Categorias

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#207]
## Descrição
Eu como usuário Admin/Owner desejo visualizar gráficos que marcam a quantidade de produtos por categoria

### Tasks: 
- [ ] Criação de gráfico de acordo com rota de categories

### Critérios de aceitação

- [ ] Estar de acordo com o protótipo
- [ ] Ser responsivo

**Comment by micaellagouveia** [comment]
Pontuação da issue:
![us30](https://user-images.githubusercontent.com/48630408/99151306-fac3d080-2678-11eb-8eb8-15d511b05e1e.png)
