### ISSUE TITLE
Filtros do histórico

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#209]
## Descrição
Aplicar filtro por busca na página de histórico

### Tasks: 
- [x] Aplicar filtro por busca de colaborador

**Comment by micaellagouveia** [comment]
Pontuação da issue:
![filtro](https://user-images.githubusercontent.com/48630408/99151319-1202be00-2679-11eb-9d2d-97af9b1bbc3f.png)
