### ISSUE TITLE
5W2H

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#3]
## Descrição
Realização da técnica durante a reunião semanal.

## Tarefas
- [x] Documentar técnica de cada membro.
- [x] Gerar documento geral da técnica.

**Comment by GabrielDVpereira** [comment]
Coloquei a minha versão do 5w2h em nosso drive na pasta Documentos/5w2h para uso na versão final

**Comment by sofiapatrocinio** [comment]
Coloquei a minha versão do 5w2h em nosso drive na pasta Documentos/5w2h para uso na versão final.

**Comment by micaellagouveia** [comment]
Coloquei a minha versão do 5w2h em nosso drive na pasta Documentos/5w2h para uso na versão final.
