### ISSUE TITLE
Identidade Visual

### ISSUE THREAD

**Issue by micaellagouveia** [UnBArqDsw/2020.1_G12_Stock#4]
## Descrição
Criação da identidade visual do produto.

## Tarefas
- [x] Logo
- [x] Documento de identidade visual

**Comment by sofiapatrocinio** [comment]
Logo escolhida:
![logo-01](https://user-images.githubusercontent.com/38709421/91055694-6575ea80-e5fb-11ea-8761-b473a7686187.png)
![logo-02](https://user-images.githubusercontent.com/38709421/91055701-673fae00-e5fb-11ea-9146-8ff23518f343.png)

**Comment by sofiapatrocinio** [comment]
O guia de identidade visual está pronto e documentado no drive, porém não estou conseguindo dar push, sempre para em alguma porcentagem. Em outros repositórios eu consigo. Já tentei várias soluções, mas vou tentar em outra máquina
