### ISSUE TITLE
BPMN - Evolução

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#72]
## Descrição
Adicionar BPMN geral.

### Tasks: 
- [x] Criar documento de metodologia BPMN geral.

### Critérios de aceitação

- [x] Estar documentado

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![bpmn](https://user-images.githubusercontent.com/48630408/93001316-8d72b280-f504-11ea-9c15-f7f054ab15fc.png)
