### ISSUE TITLE
Protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#73]
## Descrição
Fazer esboço de protótipo de baixa fidelidade.

### Tasks: 
- [x] Gabriel Alves
- [x] Gabriel Davi
- [x] Micaella
- [x] Pedro Igor
- [x] Sofia

### Critérios de aceitação

- [x] Estar no drive antes da reunião de terça (15/09)

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![baixaFidelidade](https://user-images.githubusercontent.com/48630408/93001321-99f70b00-f504-11ea-9955-b18697c90476.png)
