### ISSUE TITLE
Priorização

### ISSUE THREAD

**Issue by sofiapatrocinio** [UnBArqDsw/2020.1_G12_Stock#76]
## Descrição
Priorizar requisitos.

### Tasks: 
- [x] First things first
- [x] MOSCOW

### Critérios de aceitação

- [x] Estar documentado

**Comment by micaellagouveia** [comment]
Para esta issue foi dada a pontuação:
![priorizacao](https://user-images.githubusercontent.com/48630408/93001353-c743b900-f504-11ea-91d9-b01bdc1d4cd5.png)
